// Mocks generated by Mockito 5.4.6 from annotations
// in avalanche_flutter_sdk/test/src/chains/cchain/gas_estimator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:avalanche_flutter_sdk/src/chains/cchain/cchain_client.dart'
    as _i4;
import 'package:avalanche_flutter_sdk/src/chains/cchain/models/gas_price_options.dart'
    as _i3;
import 'package:avalanche_flutter_sdk/src/client/network_config.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNetworkConfig_0 extends _i1.SmartFake implements _i2.NetworkConfig {
  _FakeNetworkConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGasPriceOptions_1 extends _i1.SmartFake
    implements _i3.GasPriceOptions {
  _FakeGasPriceOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CChainClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCChainClient extends _i1.Mock implements _i4.CChainClient {
  MockCChainClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NetworkConfig get network => (super.noSuchMethod(
        Invocation.getter(#network),
        returnValue: _FakeNetworkConfig_0(
          this,
          Invocation.getter(#network),
        ),
      ) as _i2.NetworkConfig);

  @override
  _i5.Future<BigInt> getBalance(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [address],
        ),
        returnValue: _i5.Future<BigInt>.value(_i6.dummyValue<BigInt>(
          this,
          Invocation.method(
            #getBalance,
            [address],
          ),
        )),
      ) as _i5.Future<BigInt>);

  @override
  _i5.Future<int> getTransactionCount(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getTransactionCount,
          [address],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getBlockNumber() => (super.noSuchMethod(
        Invocation.method(
          #getBlockNumber,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<Map<String, dynamic>?> getTransactionReceipt(String? txHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionReceipt,
          [txHash],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<BigInt> getBaseFee() => (super.noSuchMethod(
        Invocation.method(
          #getBaseFee,
          [],
        ),
        returnValue: _i5.Future<BigInt>.value(_i6.dummyValue<BigInt>(
          this,
          Invocation.method(
            #getBaseFee,
            [],
          ),
        )),
      ) as _i5.Future<BigInt>);

  @override
  _i5.Future<BigInt> getMaxPriorityFeePerGas() => (super.noSuchMethod(
        Invocation.method(
          #getMaxPriorityFeePerGas,
          [],
        ),
        returnValue: _i5.Future<BigInt>.value(_i6.dummyValue<BigInt>(
          this,
          Invocation.method(
            #getMaxPriorityFeePerGas,
            [],
          ),
        )),
      ) as _i5.Future<BigInt>);

  @override
  _i5.Future<_i3.GasPriceOptions> suggestPriceOptions() => (super.noSuchMethod(
        Invocation.method(
          #suggestPriceOptions,
          [],
        ),
        returnValue:
            _i5.Future<_i3.GasPriceOptions>.value(_FakeGasPriceOptions_1(
          this,
          Invocation.method(
            #suggestPriceOptions,
            [],
          ),
        )),
      ) as _i5.Future<_i3.GasPriceOptions>);

  @override
  _i5.Future<BigInt> estimateGas({
    required String? to,
    String? from,
    BigInt? value,
    String? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateGas,
          [],
          {
            #to: to,
            #from: from,
            #value: value,
            #data: data,
          },
        ),
        returnValue: _i5.Future<BigInt>.value(_i6.dummyValue<BigInt>(
          this,
          Invocation.method(
            #estimateGas,
            [],
            {
              #to: to,
              #from: from,
              #value: value,
              #data: data,
            },
          ),
        )),
      ) as _i5.Future<BigInt>);

  @override
  _i5.Future<dynamic> call({
    required String? method,
    required List<dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #method: method,
            #params: params,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}
