import 'dart:math';
import 'dart:typed_data';

import 'package:pointycastle/export.dart' hide PublicKey;

// ---- MnemonicStrength ----

/// The number of bits of entropy used to generate a mnemonic phrase.
///
/// Source: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
///
/// | Strength | Checksum | Total bits | Word count |
/// |----------|----------|------------|------------|
/// | 128      | 4 bits   | 132 bits   | 12 words   |
/// | 160      | 5 bits   | 165 bits   | 15 words   |
/// | 192      | 6 bits   | 198 bits   | 18 words   |
/// | 224      | 7 bits   | 231 bits   | 21 words   |
/// | 256      | 8 bits   | 264 bits   | 24 words   |
enum MnemonicStrength {
  /// 128 bits of entropy - generates a 12-word mnemonic.
  words12(128),

  /// 160 bits of entropy - generates a 15-word mnemonic.
  words15(160),

  /// 192 bits of entropy - generates an 18-word mnemonic.
  words18(192),

  /// 224 bits of entropy - generates a 21-word mnemonic.
  words21(224),

  /// 256 bits of entropy - generates a 24-word mnemonic.
  words24(256);

  const MnemonicStrength(this.bits);

  /// The number of bits of entropy for this strength level.
  final int bits;

  /// The number of bytes of entropy for this strength level.
  int get bytes => bits ~/ 8;

  /// The number of checksum bits appended after the entropy.
  ///
  /// Per BIP-39: CS = ENT / 32
  int get checksumBits => bits ~/ 32;

  /// The total number of bits (entropy + checksum).
  ///
  /// Per BIP-39: ENT + CS
  int get totalBits => bits + checksumBits;

  /// The number of words in the resulting mnemonic.
  ///
  /// Per BIP-39: MS = (ENT + CS) / 11
  int get wordCount => totalBits ~/ 11;
}

// ---- Entropy ----

/// Generates and validates BIP-39 entropy.
///
/// Entropy is the cryptographically secure random source from which
/// a mnemonic phrase is derived. The entropy bytes plus a SHA256
/// checksum are converted to word indices into a BIP-39 wordlist.
///
/// Source: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
///
/// "First, an initial entropy of ENT bits is generated. A checksum
/// is generated by taking the first ENT/32 bits of its SHA256 hash.
/// This checksum is appended to the end of the initial entropy."
class Entropy {
  Entropy._();

  // ---- Public API: Generate ----

  /// Generates cryptographically secure entropy of the given [strength].
  ///
  /// Defaults to [MnemonicStrength.words12] (128 bits / 12 words).
  ///
  /// Uses [FortunaRandom] seeded with [Random.secure()] - the same
  /// CSPRNG used for [PrivateKey] generation, ensuring consistent
  /// security standards across the crypto layer.
  static Uint8List generate({
    MnemonicStrength strength = MnemonicStrength.words12,
  }) {
    final secureRandom = _buildSecureRandom();
    final entropy = Uint8List(strength.bytes);
    for (var i = 0; i < entropy.length; i++) {
      entropy[i] = secureRandom.nextUint8();
    }
    return entropy;
  }

  // ---- Public API: Validate ----

  /// Validates that [entropy] has a length corresponding to one of
  /// the five valid BIP-39 entropy sizes (128, 160, 192, 224, 256 bits).
  ///
  /// Throws [ArgumentError] if the length is invalid.
  static void validate(Uint8List entropy) {
    final validBytes = MnemonicStrength.values.map((s) => s.bytes).toSet();
    if (!validBytes.contains(entropy.length)) {
      throw ArgumentError(
        'Invalid entropy length: ${entropy.length} bytes '
        '(${entropy.length * 8} bits). '
        'Valid lengths are: ${validBytes.map(
              (b) => '$b bytes '
                  '(${b * 8} bits)',
            ).join(', ')}.',
      );
    }
  }

  // ---- Public API: Checksum ----

  /// Computes the BIP-39 checksum for the given [entropy].
  ///
  /// Returns the first [MnemonicStrength.checksumBits] bits of the
  /// SHA256 hash of the entropy, as an integer.
  ///
  /// Per BIP-39: CS = first (ENT / 32) bits of SHA256(entropy)
  static int computeChecksum(Uint8List entropy) {
    validate(entropy);
    final hash = _sha256(entropy);
    final strength = _strengthFromBytes(entropy.length);
    // Extract the first `checksumBits` bits from the first hash byte.
    // e.g. 4 bits: shift right by 4 → take the upper nibble of hash[0]
    return hash[0] >> (8 - strength.checksumBits);
  }

  // ---- Public API: Combined bits ----

  /// Returns the combined bit string: entropy bits + checksum bits.
  ///
  /// This is the input for word index computation in the mnemonic layer.
  ///
  /// Per BIP-39: the concatenated bits are split into groups of 11 bits,
  /// each encoding a number from 0-2047 (an index into the wordlist).
  static List<int> toBits(Uint8List entropy) {
    validate(entropy);
    final strength = _strengthFromBytes(entropy.length);
    final bits = <int>[];

    // Convert entropy bytes to individual bits (MSB first)
    for (final byte in entropy) {
      for (var i = 7; i >= 0; i--) {
        bits.add((byte >> i) & 1);
      }
    }

    // Append checksum bits
    final checksum = computeChecksum(entropy);
    for (var i = strength.checksumBits - 1; i >= 0; i--) {
      bits.add((checksum >> i) & 1);
    }

    return bits;
  }

  // ---- Internal Helpers ----

  static Uint8List _sha256(Uint8List data) {
    final digest = SHA256Digest();
    return digest.process(data);
  }

  static MnemonicStrength _strengthFromBytes(int bytes) {
    return MnemonicStrength.values.firstWhere(
      (s) => s.bytes == bytes,
    );
  }

  static SecureRandom _buildSecureRandom() {
    final secureRandom = FortunaRandom();
    final random = Random.secure();
    final seed = Uint8List.fromList(
      List<int>.generate(32, (_) => random.nextInt(256)),
    );
    secureRandom.seed(KeyParameter(seed));
    return secureRandom;
  }
}
